language: python
python:
  - "3.5"
  - "3.6"
env:
  global:
    - BIBLAT_PROCESS_CONFIG=testing
install:
  - pip install -r requirements.txt
script:
  - coverage run --source biblat_process setup.py test
  - coverage report
