# -*- coding: utf-8 -*-

paises = {
    'Brasil': 'BR',
    'México': 'MX',
    'Colombia': 'CO',
    'Argentina': 'AT',
    'Cuba': 'CU',
    'Chile': 'CL',
    'Venezuela': 'VE',
    'Estados Unidos de América': 'US',
    'España': 'ES',
    'Costa Rica': 'CR',
    'Perú': 'PE',
    'Francia': 'FR',
    'Reino Unido': 'GB',
    'Uruguay': 'UY',
    'Alemania': 'DE',
    'Ecuador': 'EC',
    'Canadá': 'CA',
    'Italia': 'IT',
    'Portugal': 'PT',
    'Puerto Rico': 'PR',
    'India': 'IN',
    'China': 'CN',
    'Guatemala': 'GT',
    'Bolivia': 'BO',
    'Japón': 'JP',
    'Panamá': 'PA',
    'Turquía': 'TR',
    'Holanda': 'NL',
    'Suiza': 'CH',
    'Australia': 'AU',
    'República Dominicana': 'DO',
    'Bélgica': 'BE',
    'Irán': 'IR',
    'Nicaragua': 'NI',
    'El Salvador': 'SV',
    'Rusia': 'RU',
    'Israel': 'IL',
    'Suecia': 'SE',
    'República Federal Alemana': 'DE',
    'Paraguay': 'PY',
    'Polonia': 'PL',
    'Nigeria': 'NG',
    'Egipto': 'EG',
    'Honduras': 'HN',
    'Jamaica': 'JM',
    'Austria': 'AT',
    'Corea del Sur': 'KR',
    'Pakistán': 'PK',
    'Unión Soviética': 'SU',
    'Taiwán': 'TW',
    'Dinamarca': 'DK',
    'Grecia': 'GR',
    'República Checa': 'CZ',
    'Sudáfrica': 'ZA',
    'Finlandia': 'FI',
    'Malasia': 'MY',
    'Tailandia': 'TH',
    'Noruega': 'NO',
    'Hungría': 'HU',
    'Nueva Zelanda': 'NZ',
    'Rumania': 'RO',
    'Trinidad y Tobago': 'TT',
    'Serbia': 'RS',
    'Barbados': 'BB',
    'Arabia Saudita': 'SA',
    'Kenia': 'KE',
    'Bulgaria': 'BG',
    'Croacia': 'HR',
    'República Democrática Alemana': 'DE',
    'Túnez': 'TN',
    'Ucrania': 'UA',
    'Jordania': 'JO',
    'Irlanda': 'IE',
    'Bangladesh': 'BD',
    'Marruecos': 'MA',
    'Argelia': 'DZ',
    'Belice': 'BZ',
    'Eslovaquia': 'SK',
    'Eslovenia': 'SI',
    'Mozambique': 'MZ',
    'Checoslovaquia': 'CS',
    'Vietnam': 'VN',
    'Angola': 'AO',
    'Haití': 'HT',
    'Camerún': 'CM',
    'Yugoslavia': 'YU',
    'Singapur': 'SG',
    'Filipinas': 'PH',
    'Indonesia': 'ID',
    'Emiratos Arabes Unidos': 'AE',
    'Sri Lanka': 'LK',
    'Zimbabwe': 'ZW',
    'Guyana': 'GY',
    'Senegal': 'SN',
    'Etiopía': 'ET',
    'Líbano': 'LB',
    'Malta': 'MT',
    'Irak': 'IQ',
    'Luxemburgo': 'LU',
    'Siria': 'SY',
    'Sudán': 'SD',
    'Omán': 'OM',
    'Kuwait': 'KW',
    'Surinam': 'SR',
    'Bosnia y Herzegovina': 'BA',
    'Ghana': 'GH',
    'Cabo Verde': 'CV',
    'Guinea Bissau': 'GW',
    'Baréin': 'BH',
    'Vaticano': 'VA',
    'Macedonia': 'MK',
    'Letonia': 'LV',
    'Tanzania': 'TZ',
    'Qatar': 'QA',
    'Armenia': 'AM',
    'Costa de Marfil': 'CI',
    'Kazajistán': 'KZ',
    'Lituania': 'LT',
    'Bielorrusia': 'BY',
    'Madagascar': 'MG',
    'Yemen': 'YE',
    'Estonia': 'EE',
    'Libia': 'LY',
    'Bahamas': 'BS',
    'Islandia': 'IS',
    'Serbia y Montenegro': 'RS',
    'Palestina': 'PS',
    'Chipre': 'CY',
    'Guayana Francesa': 'GF',
    'Malawi': 'MW',
    'Islas Vírgenes Norteamericanas': 'VI',
    'Uzbekistán': 'UZ',
    'Georgia': 'GE',
    'Uganda': 'UG',
    'Nepal': 'NP',
    'Antillas Holandesas': 'AN',
    'Santa Lucía': 'LC',
    'Granada': 'GD',
    'Ruanda': 'RW',
    'Dominica': 'DM',
    'Azerbaiyán': 'AZ',
    'Guinea': 'GN',
    'Mauricio': 'MU',
    'Mëxico': 'MX',
    'Islas Fiji': 'FJ',
    'República Democrática del Congo': 'CD',
    'Islas Caimán': 'KY',
    'Aruba': 'AW',
    'Mongolia': 'MN',
    'Zaire': 'ZR',
    'Martinica': 'MQ',
    'Togo': 'TG',
    'Republic of Mordovia': 'RU',
    'Congo': 'CG',
    'Albania': 'AL',
    'Mónaco': 'MC',
    'República de San Marino': 'SM',
    'Burkina Faso': 'BF',
    'Nueva Caledonia': 'NC',
    'Sudán del Sur': 'SD',
    'Alto Volta': 'BF',
    'Montenegro': 'ME',
    'Añemania': 'DE',
    '(México': 'MX',
    'Gambia': 'GM',
    'Zambia': 'ZM',
    'Bután': 'BT',
    'Japòn': 'JP',
    'Namibia': 'NA',
    '(Colombia': 'CO',
    'Lima': 'PE',
    'Curazao': 'CW',
    'Tahití': 'PF',
    'Timor Oriental': 'TL',
    'Benín': 'BJ',
    'Papúa Nueva Guinea': 'PG',
    'Andorra': 'AD',
    'República Centroafricana': 'CF',
    'Myanmar': 'MM',
    'Islas Salomón': 'SB',
    '(Chile)': 'CL',
    'Saint Kitts and Nevis': 'KN',
    'Laos': 'LA',
    'Slovenia': 'SI',
    'Sierra Leona': 'SL',
    'San Vicente y las Granadinas': 'VC',
    'Camboya': 'KH',
    'Burundi': 'BI',
    'Turkmenistán': 'TM',
    'Italia)': 'IT',
    'Chad': 'TD',
    'Mèxico': 'MX',
    'Lesotho': 'LS',
    'Moldavia': 'MD',
    'Brasil /': 'BR',
    'Botsuana': 'BW',
    'Gabón': 'GA',
}

idioma = {
    'Español' : ['spa'],
    'Portugués' : ['por'],
    'Inglés' : ['eng'],
    'Español, inglés' : ['spa', 'eng'],
    'Portugués, inglés' : ['por', 'eng'],
    'Francés' : ['fra'],
    'Español, portugués, inglés' : ['spa', 'por', 'eng'],
    'Italiano' : ['ita'],
    'Alemán' : ['deu'],
    'Español, portugués' : ['spa', 'por'],
    'Español, francés' : ['spa', 'fra'],
    'Portugués, francés' : ['por', 'fra'],
    'Latín' : ['lat'],
    'Español, náhuatl' : ['spa', 'nah'],
    'Español, italiano' : ['spa', 'ita'],
    'Náhuatl' : ['nah'],
    'Español, kuna' : ['spa', 'kvn'],
    'Maya' : ['myn'],
    'Español, alemán' : ['spa', 'deu'],
    'Gallego' : ['glg'],
    'Español, latín' : ['spa', 'lat'],
    'Banca' : ['zxx'],
    'Español, Inglés' : ['spa', 'eng'],
    'Español, inglés, francés' : ['spa', 'eng', 'fra'],
    'Español, mapuche' : ['spa', 'arn'],
    'Español, portugués, inglés, francés' : ['spa', 'por', 'eng', 'fra'],
    'Español, Ch\'ol' : ['spa', 'ctu'],
    'Náhuatl, inglés' : ['nah', 'eng'],
    'Portugués, alemán' : ['por', 'deu'],
    'Portugués, italiano' : ['por', 'ita'],
    'Portugués, latín' : ['por', 'lat'],
    'Español, griego, latín' : ['spa', 'grk' 'lat'],
}
